  
name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action
      uses: shfaizan/face-gan@master
    - uses: actions/upload-artifact@v1
